(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Nicholas Gonzalez, created 2014-12-02."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((Background-mode . light)
      ;;      (background-color . "misty rose")
      (background-color . "ivory1")
      (background-mode . light)
      (border-color . "white")
      (cursor-color . "slateblue")
      (foreground-color . "black")
      (mouse-color . "slateblue"))
     ((ac-fuzzy-cursor-color . "red")
      (apropos-match-face . match)
      (browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "black")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (eval-sexp-fu-flash-error-face . eval-sexp-fu-flash-error)
      (eval-sexp-fu-flash-face . eval-sexp-fu-flash)
      (gnus-mouse-face . highlight)
      (gnus-summary-selected-face . gnus-summary-selected)
      (hl-line-face . hl-line)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (magit-item-highlight-face . magit-item-highlight)
      (org-goto-interface . outline)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight)
      (win-switch-feedback-background-color . "DeepPink3")
      (win-switch-feedback-foreground-color . "black"))
     (default ((t (:stipple nil :background "misty rose" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Highline-face ((t (:background "SeaGreen"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (ac-candidate-face ((t (:background "gray60" :foreground "black"))))
     (ac-candidate-mouse-face ((t (:background "blue" :foreground "white"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "gray60" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "black"))))
     (ac-nrepl-candidate-face ((t (:background "gray60" :foreground "black"))))
     (ac-nrepl-selection-face ((t (:background "deep pink" :foreground "black"))))
     (ac-selection-face ((t (:background "deep pink" :foreground "black"))))
     (ac-yasnippet-candidate-face ((t (:background "gray60" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:background "deep pink" :foreground "black"))))
     (ace-jump-face-background ((t (:foreground "gray40"))))
     (ace-jump-face-foreground ((t (:foreground "red" :underline nil))))
     (apropos-function-button ((t (:foreground "#4c83ff"))))
     (apropos-keybinding ((t (:underline t))))
     (apropos-misc-button ((t (:foreground "yellow3"))))
     (apropos-property ((t (:foreground "black"))))
     (apropos-symbol ((t (:foreground "deep pink"))))
     (apropos-variable-button ((t (:foreground "dark green"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "black"))))
     (border ((t (:background "white"))))
     (border-glyph ((t (nil))))
     (browse-kill-ring-current-entry-face ((t (:background "gray10"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (button ((t (:background "white" :foreground "RoyalBlue3" :underline t))))
     (c-annotation-face ((t (:foreground "darkblue"))))
     (calc-nonselected-face ((t (:italic t :foreground "grey50" :slant italic))))
     (calc-selected-face ((t (:bold t :weight bold))))
     (calendar-today ((t (:background "Spring Green" :foreground "Brown" :underline t))))
     (change-log-acknowledgment ((t (:italic t :background "seashell" :slant italic))))
     (change-log-conditionals ((t (:foreground "black"))))
     (change-log-date ((t (:background "lemonChiffon"))))
     (change-log-email ((t (:foreground "black"))))
     (change-log-file ((t (:bold t :underline t :weight bold))))
     (change-log-function ((t (:foreground "black"))))
     (change-log-list ((t (:foreground "blue"))))
     (change-log-name ((t (:foreground "darkblue"))))
     (cider-docview-emphasis-face ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline t :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-docview-literal-face ((t (:background "lemonChiffon"))))
     (cider-docview-strong-face ((t (:bold t :stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline t :slant normal :weight bold :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-docview-table-border-face ((t (:foreground "grey50"))))
     (cider-error-highlight-face ((t (:background "white"))))
     (cider-repl-err-output-face ((t (:foreground "deeppink"))))
     (cider-repl-input-face ((t (:bold t :weight bold))))
     (cider-repl-output-face ((t (:background "lemonChiffon"))))
     (cider-repl-prompt-face ((t (:foreground "blue"))))
     (cider-repl-result-face ((t (nil))))
     (cider-stacktrace-error-class-face ((t (:bold t :background "white" :foreground "Red" :weight bold))))
     (cider-stacktrace-error-message-face ((t (:background "lemonChiffon"))))
     (cider-stacktrace-face ((t (:stipple nil :background "ivory" :foreground "black" :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-stacktrace-filter-hidden-face ((t (:background "black" :foreground "ivory" :underline nil :weight normal))))
     (cider-stacktrace-filter-shown-face ((t (:foreground "#4c83ff"))))
     (cider-stacktrace-fn-face ((t (:bold t :stipple nil :background "ivory" :foreground "black" :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-stacktrace-ns-face ((t (:italic t :background "black" :foreground "ivory" :slant italic))))
     (cider-test-error-face ((t (:background "orange1"))))
     (cider-test-failure-face ((t (:background "orange red"))))
     (cider-test-success-face ((t (:background "green" :foreground "black"))))
     (cider-warning-highlight-face ((t (:underline (:style wave :color "yellow")))))
     (clojure-character-face ((t (:background "lemonChiffon"))))
     (clojure-interop-method-face ((t (:background "pale green" :foreground "dark slate blue"))))
     (clojure-keyword-face ((t (:foreground "darkblue"))))
     (clojure-test-error-face ((t (:background "orange1"))))
     (clojure-test-failure-face ((t (:background "orange red"))))
     (clojure-test-success-face ((t (:background "green" :foreground "black"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:background "lemonChiffon"))))
     (compilation-error ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-info ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-line-number ((t (:foreground "blue"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (:bold t :foreground "maroon" :weight bold))))
     (cparen-around-begin-face ((t (:foreground "maroon"))))
     (cparen-around-conditional-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (cparen-around-define-face ((t (:bold t :foreground "Blue" :weight bold))))
     (cparen-around-lambda-face ((t (:foreground "LightSeaGreen"))))
     (cparen-around-letdo-face ((t (:bold t :foreground "LightSeaGreen" :weight bold))))
     (cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
     (cparen-around-set!-face ((t (:foreground "OrangeRed"))))
     (cparen-around-syntax-rules-face ((t (:foreground "Magenta"))))
     (cparen-around-vector-face ((t (:foreground "chocolate"))))
     (cparen-binding-face ((t (:foreground "ForestGreen"))))
     (cparen-binding-list-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (cparen-conditional-clause-face ((t (:foreground "RoyalBlue"))))
     (cparen-normal-paren-face ((t (:foreground "grey50"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "slateblue" :foreground "black"))))
     (custom-button-face ((t (:background "white" :foreground "azure"))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation-face ((t (:background "white" :foreground "blue"))))
     (custom-face-tag-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (custom-group-tag-face ((t (:bold t :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-face-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "helv"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "white" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "helv"))))
     (diary ((t (:background "navy" :foreground "yellow"))))
     (diff-added ((t (:foreground "Green"))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:background "gray10" :foreground "deep pink"))))
     (diff-function ((t (:background "gray10" :foreground "#4c83ff"))))
     (diff-header ((t (:background "gray10" :foreground "#4c83ff"))))
     (diff-hunk-header ((t (:background "gray10" :foreground "#4c83ff"))))
     (diff-index ((t (:background "gray10" :foreground "deep pink"))))
     (diff-indicator-added ((t (:foreground "green"))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:foreground "red"))))
     (diff-nonexistent ((t (:background "gray10" :foreground "deep pink"))))
     (diff-refine-added ((t (:background "#aaffaa"))))
     (diff-refine-change ((t (:background "#ffff55"))))
     (diff-refine-removed ((t (:background "#ffbbbb"))))
     (diff-removed ((t (:foreground "Red"))))
     (dircolors-face-asm ((t (:foreground "Tan"))))
     (dircolors-face-backup ((t (:foreground "darkslategrey"))))
     (dircolors-face-compress ((t (:foreground "firebrick"))))
     (dircolors-face-dir ((t (:foreground "orange"))))
     (dircolors-face-doc ((t (:foreground "red"))))
     (dircolors-face-dos ((t (:foreground "darkred"))))
     (dircolors-face-emacs ((t (:foreground "purple"))))
     (dircolors-face-exec ((t (:foreground "red"))))
     (dircolors-face-html ((t (:foreground "magenta"))))
     (dircolors-face-img ((t (:foreground "yellow"))))
     (dircolors-face-lang ((t (:foreground "lightblue"))))
     (dircolors-face-lang-interface ((t (:foreground "deepskyblue"))))
     (dircolors-face-make ((t (:foreground "seagreen"))))
     (dircolors-face-objet ((t (:foreground "orangered"))))
     (dircolors-face-package ((t (:foreground "firebrick"))))
     (dircolors-face-paddb ((t (:foreground "Orange"))))
     (dircolors-face-ps ((t (:foreground "brown"))))
     (dircolors-face-sound ((t (:foreground "yellow"))))
     (dircolors-face-tar ((t (:foreground "firebrick"))))
     (dircolors-face-text ((t (:foreground "red"))))
     (dircolors-face-yacc ((t (:foreground "dodgerblue"))))
     (dired-directory ((t (:bold t :underline t :weight bold))))
     (dired-flagged ((t (:bold t :foreground "Red1" :weight bold))))
     (dired-header ((t (:foreground "black"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "darkblue"))))
     (dired-marked ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (dired-perm-write ((t (:foreground "#B2B2B2"))))
     (dired-symlink ((t (:foreground "blue"))))
     (dired-warning ((t (:bold t :foreground "Red" :weight bold))))
     (ediff-current-diff-A ((t (:background "#ffdddd"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "#ddffdd"))))
     (ediff-current-diff-C ((t (:background "#ffffaa"))))
     (ediff-even-diff-A ((t (nil))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (nil))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "#ffbbbb"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "#aaffaa"))))
     (ediff-fine-diff-C ((t (:background "#ffff55"))))
     (ediff-odd-diff-A ((t (nil))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (nil))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (epa-field-body ((t (:italic t :slant italic))))
     (epa-field-name ((t (:bold t :weight bold))))
     (epa-mark ((t (:bold t :foreground "red" :weight bold))))
     (epa-string ((t (:foreground "blue4"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :slant italic))))
     (erc-action-face ((t (:foreground "#FF6400"))))
     (erc-current-nick-face ((t (:foreground "#FBDE2D"))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (:foreground "#61CE3C"))))
     (erc-direct-msg-face ((t (:foreground "orange"))))
     (erc-error-face ((t (:foreground "red"))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-input-face ((t (:foreground "#4c83ff"))))
     (erc-inverse-face ((t (:background "white" :foreground "blue"))))
     (erc-keyword-face ((t (:foreground "deep pink"))))
     (erc-my-nick-face ((t (:bold t :foreground "deep pink" :weight bold))))
     (erc-nick-default-face ((t (:foreground "grey57"))))
     (erc-nick-msg-face ((t (:foreground "deep pink"))))
     (erc-notice-face ((t (:bold t :foreground "grey26" :weight bold))))
     (erc-pal-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-timestamp-face ((t (:foreground "dim gray"))))
     (erc-underline-face ((t (:underline t))))
     (error ((t (:bold t :foreground "Red1" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (eval-sexp-fu-flash ((t (:background "white" :foreground "red"))))
     (eval-sexp-fu-flash-error ((t (:bold t :foreground "red" :weight bold))))
     (extra-whitespace-face ((t (:background "pale green"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "courier"))))
     (flx-highlight-face ((t (:background "white" :foreground "deep pink"))))
     (flymake-errline ((t (:bold t :foreground "Red1" :weight bold))))
     (flymake-warnline ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "navy"))))
     (font-latex-sedate-face ((t (:foreground "DimGray"))))
     (font-latex-string-face ((t (nil))))
     (font-latex-warning-face ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "black"))))
     ;;     (font-lock-comment-delimiter-face ((t (:background "pink" :foreground "firebrick"))))
     (font-lock-comment-delimiter-face ((t (:background "LightCyan2" :foreground "firebrick"))))
     (font-lock-comment-face ((t (:italic t :bold t :foreground "firebrick" :slant italic :weight bold))))
     (font-lock-constant-face ((t (:foreground "darkblue"))))
     ;;     (font-lock-doc-face ((t (:italic t :background "light blue" :slant italic))))
     (font-lock-doc-face ((t (:italic t :background "pale turquoise" :slant italic))))
     (font-lock-doc-string-face ((t (:background "aquamarine" :foreground "deep pink"))))
     (font-lock-function-name-face ((t (:bold t :background "sky blue" :underline t :weight bold))))
     (font-lock-keyword-face ((t (:foreground "blue"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:background "pale green" :foreground "dark slate blue"))))
     (font-lock-reference-face ((t (:background "DarkTurquoise" :foreground "Navy"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#00BD41"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:background "lemonChiffon"))))
     (font-lock-type-face ((t (:bold t :foreground "black" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :underline t :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "grey95"))))
     (git-commit-branch-face ((t (:background "black" :foreground "#FF6400"))))
     (git-commit-comment-action-face ((t (:background "black" :foreground "#FF6400"))))
     (git-commit-comment-file-face ((t (:background "lemonChiffon"))))
     (git-commit-comment-heading-face ((t (:background "black" :foreground "deep pink"))))
     (git-commit-known-pseudo-header-face ((t (:foreground "blue"))))
     (git-commit-no-branch-face ((t (:background "black" :foreground "#FF6400"))))
     (git-commit-nonempty-second-line-face ((t (:background "black" :foreground "#FBDE2D"))))
     (git-commit-note-face ((t (:background "lemonChiffon"))))
     (git-commit-overlong-summary-face ((t (:bold t :foreground "Red" :weight bold))))
     (git-commit-pseudo-header-face ((t (:background "lemonChiffon"))))
     (git-commit-summary-face ((t (:background "black" :foreground "white"))))
     (git-gutter:added ((t (:background "gray5" :foreground "#61CE3C"))))
     (git-gutter:deleted ((t (:background "gray5" :foreground "gray10"))))
     (git-gutter:modified ((t (:background "gray5" :foreground "#4c83ff"))))
     (git-gutter:separator ((t (:bold t :foreground "cyan" :weight bold))))
     (git-gutter:unchanged ((t (:background "grey5"))))
     (git-rebase-description ((t (nil))))
     (git-rebase-hash ((t (:foreground "firebrick"))))
     (git-rebase-killed-action ((t (:italic t :background "seashell" :strike-through t :slant italic))))
     (glsl-builtin-face ((t (:foreground "#FF6400"))))
     (glsl-keyword-face ((t (:foreground "#FBDE2D"))))
     (glsl-type-face ((t (:foreground "#4c83ff"))))
     (glsl-variable-name-face ((t (:foreground "grey57"))))
     (glyphless-char ((t (:height 0.6))))
     (gnus-group-mail-1 ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "HotPink3"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "magenta4"))))
     (gnus-group-mail-low ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "DeepPink4"))))
     (gnus-group-news-1 ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "ForestGreen"))))
     (gnus-group-news-2 ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkGreen"))))
     (gnus-splash ((t (:foreground "#888888"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "cyan4" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "firebrick" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "firebrick"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (grep-context-face ((t (:background "deep pink" :foreground "black"))))
     (grep-hit-face ((t (:background "red" :foreground "black"))))
     (grep-match-face ((t (:background "deep pink" :foreground "black"))))
     (gui-element ((t (:background "#aa0000" :foreground "#00aa00"))))
     (haskell-constructor-face ((t (:foreground "black"))))
     (haskell-default-face ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (haskell-definition-face ((t (:bold t :underline t :weight bold))))
     (haskell-keyword-face ((t (:foreground "blue"))))
     (haskell-literate-comment-face ((t (:background "lemonChiffon"))))
     (haskell-operator-face ((t (:foreground "black"))))
     (haskell-pragma-face ((t (:italic t :background "seashell" :slant italic))))
     (header-line ((t (:bold t :background "grey90" :foreground "grey20" :box nil :underline t :weight bold))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hideshowvis-hidable-face ((t (:foreground "#ccc" :box 1))))
     (highlight ((t (:background "mistyRose" :foreground "black"))))
     (highline-face ((t (:background "#426BEE"))))
     (hl-line ((t (:background "light gray"))))
     (hl-sexp-face ((t (:background "grey9"))))
     (hlt-property-highlight ((t (:background "Wheat"))))
     (holiday ((t (:background "orangered" :foreground "lightyellow"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (ibuffer-git-add-face ((t (:foreground "green"))))
     (ibuffer-git-del-face ((t (:foreground "red"))))
     (ido-first-match ((t (:bold t :foreground "#007B22" :weight bold))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red" :weight bold))))
     (ido-indicator ((t (:background "deep pink" :foreground "black"))))
     (ido-only-match ((t (:bold t :foreground "#007B22" :weight bold))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:bold t :foreground "#D61619" :weight bold))))
     (ido-subdir-face ((t (:foreground "red"))))
     (ido-virtual ((t (:foreground "black"))))
     (info-header-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-header-xref ((t (:bold t :foreground "cyan" :weight bold))))
     (info-menu-5 ((t (:foreground "red1"))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-xref ((t (:bold t :foreground "cyan" :weight bold))))
     (isearch ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "red4"))))
     (iswitchb-current-match ((t (:bold t :underline t :weight bold))))
     (iswitchb-invalid-regexp ((t (:bold t :foreground "Red" :weight bold))))
     (iswitchb-single-match ((t (:italic t :background "seashell" :slant italic))))
     (iswitchb-virtual-matches ((t (:foreground "black"))))
     (italic ((t (nil))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (js2-error ((t (:foreground "red"))))
     (js2-external-variable ((t (:foreground "orange"))))
     (js2-function-call ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (js2-function-param ((t (:foreground "SeaGreen"))))
     (js2-instance-member ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter ((t (:foreground "dark khaki"))))
     (js2-jsdoc-html-tag-name ((t (:foreground "rosybrown"))))
     (js2-jsdoc-tag ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value ((t (:foreground "PeachPuff3"))))
     (js2-private-function-call ((t (:foreground "goldenrod"))))
     (js2-private-member ((t (:foreground "PeachPuff3"))))
     (js2-warning ((t (:underline "orange"))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "RoyalBlue3" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (log-edit-header ((t (:foreground "blue"))))
     (log-edit-summary ((t (:bold t :underline t :weight bold))))
     (log-edit-unknown-header ((t (:italic t :background "seashell" :slant italic))))
     (magit-branch ((t (:foreground "gold"))))
     (magit-cherry-equivalent ((t (:foreground "magenta"))))
     (magit-cherry-unmatched ((t (:foreground "cyan"))))
     (magit-diff-add ((t (:foreground "green"))))
     (magit-diff-del ((t (:foreground "red"))))
     (magit-diff-file-header ((t (:background "gray10" :foreground "deep pink"))))
     (magit-diff-hunk-header ((t (:foreground "orange"))))
     (magit-diff-merge-current ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-merge-diff3-separator ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-merge-proposed ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-merge-separator ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-none ((t (:foreground "grey50"))))
     (magit-item-highlight ((t (:background "gray15"))))
     (magit-item-mark ((t (:background "mistyRose" :foreground "black"))))
     (magit-key-mode-args-face ((t (:background "gray85"))))
     (magit-key-mode-button-face ((t (:foreground "black"))))
     (magit-key-mode-header-face ((t (:foreground "blue"))))
     (magit-key-mode-switch-face ((t (:bold t :foreground "Red" :weight bold))))
     (magit-log-author ((t (:foreground "firebrick"))))
     (magit-log-date ((t (nil))))
     (magit-log-graph ((t (:foreground "grey11"))))
     (magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-head-label-bisect-skip ((t (:background "light goldenrod" :foreground "dark goldenrod" :box 1))))
     (magit-log-head-label-default ((t (:background "Grey50" :box 1))))
     (magit-log-head-label-head ((t (:background "Grey20" :foreground "White" :box 1))))
     (magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-head-label-wip ((t (:background "Grey07" :foreground "LightSkyBlue4" :box 1))))
     (magit-log-message ((t (nil))))
     (magit-log-reflog-label-amend ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-reflog-label-checkout ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-reflog-label-cherry-pick ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-reflog-label-commit ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-reflog-label-merge ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-reflog-label-other ((t (:background "Grey50" :box 1))))
     (magit-log-reflog-label-rebase ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-reflog-label-remote ((t (:background "Grey50" :box 1))))
     (magit-log-reflog-label-reset ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-sha1 ((t (:foreground "firebrick"))))
     (magit-process-ng ((t (:foreground "red"))))
     (magit-process-ok ((t (:foreground "green"))))
     (magit-section-title ((t (:foreground "deep pink"))))
     (magit-signature-bad ((t (:foreground "red"))))
     (magit-signature-good ((t (:foreground "green"))))
     (magit-signature-none ((t (nil))))
     (magit-signature-untrusted ((t (:foreground "cyan"))))
     (magit-tag ((t (:background "LemonChiffon1" :foreground "goldenrod4"))))
     (magit-whitespace-warning-face ((t (:background "red"))))
     (markdown-blockquote-face ((t (:background "lemonChiffon"))))
     (markdown-bold-face ((t (:foreground "#FF6400"))))
     (markdown-comment-face ((t (:italic t :background "seashell" :slant italic))))
     (markdown-header-face ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-1 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-2 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-3 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-4 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-5 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-6 ((t (:bold t :underline t :weight bold))))
     (markdown-inline-code-face ((t (:foreground "#4c83ff"))))
     (markdown-italic-face ((t (:italic t :foreground "#FF6400" :slant italic))))
     (markdown-link-face ((t (:foreground "#FBDE2D"))))
     (markdown-link-title-face ((t (:italic t :background "seashell" :slant italic))))
     (markdown-list-face ((t (:foreground "#8B8989"))))
     (markdown-math-face ((t (:background "lemonChiffon"))))
     (markdown-pre-face ((t (:foreground "#4c83ff"))))
     (markdown-reference-face ((t (:foreground "black"))))
     (markdown-url-face ((t (:foreground "#61CE3C"))))
     (match ((t (:background "white" :foreground "red"))))
     (mc/cursor-face ((t (nil))))
     (mc/region-face ((t (:background "lavender" :foreground "black"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "red"))))
     (message-header-cc ((t (:foreground "MidnightBlue"))))
     (message-header-name ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "steel blue"))))
     (message-header-subject ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "brown"))))
     (minibuffer-prompt ((t (:foreground "#000"))))
     (mode-line ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (mode-line-buffer-id ((t (:background "Royalblue4" :foreground "lawn green"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#ddd" :foreground "#000"))))
     (modeline ((t (:background "Royalblue4" :foreground "lawn green"))))
     (modeline-mousable ((t (:background "Royalblue4" :foreground "lawn green"))))
     (modeline-mousable-minor-mode ((t (:background "Royalblue4" :foreground "lawn green"))))
     (mouse ((t (:background "slateblue"))))
     (naeu-blue-face ((t (:background "black" :foreground "medium slate blue"))))
     (naeu-green-face ((t (:background "black" :foreground "green"))))
     (naeu-grey-face ((t (:background "black" :foreground "gray30"))))
     (naeu-orange-face ((t (:background "black" :foreground "#FBDE2D"))))
     (naeu-pink-face ((t (:background "black" :foreground "deep pink"))))
     (naeu-red-face ((t (:background "black" :foreground "orange"))))
     (next-error ((t (:background "deep pink" :foreground "black"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (org-agenda-calendar-event ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-agenda-calendar-sexp ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-agenda-clocking ((t (:background "yellow"))))
     (org-agenda-column-dateline ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-agenda-current-time ((t (:foreground "DarkGoldenrod"))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-diary ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-filter-category ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-agenda-filter-regexp ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-agenda-filter-tags ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-agenda-restriction-lock ((t (:background "#eeeeee"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:italic t :background "seashell" :slant italic))))
     (org-block-end-line ((t (:italic t :background "seashell" :slant italic))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-checkbox-statistics-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-clock-overlay ((t (:background "yellow1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-date-selected ((t (:background "Red1"))))
     (org-default ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-document-info ((t (:foreground "midnight blue"))))
     (org-document-info-keyword ((t (:foreground "grey50"))))
     (org-document-title ((t (:bold t :foreground "midnight blue" :weight bold))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "white"))))
     (org-latex-and-related ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:bold t :underline t :weight bold))))
     (org-level-2 ((t (:foreground "black"))))
     (org-level-3 ((t (:foreground "blue"))))
     (org-level-4 ((t (:italic t :background "seashell" :slant italic))))
     (org-level-5 ((t (:foreground "black"))))
     (org-level-6 ((t (:foreground "darkblue"))))
     (org-level-7 ((t (:foreground "black"))))
     (org-level-8 ((t (:background "lemonChiffon"))))
     (org-link ((t (:foreground "RoyalBlue3" :underline t))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:foreground "SaddleBrown"))))
     (org-meta-line ((t (:italic t :background "seashell" :slant italic))))
     (org-mode-line-clock ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-mode-line-clock-overrun ((t (:bold t :background "red" :foreground "navy" :underline t :weight bold))))
     (org-priority ((t (:foreground "blue"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey50"))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "blue"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-tag-group ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-verse ((t (:foreground "grey50"))))
     (org-warning ((t (:bold t :foreground "Red" :weight bold))))
     (outline-1 ((t (:bold t :underline t :weight bold))))
     (outline-2 ((t (:foreground "black"))))
     (outline-3 ((t (:foreground "blue"))))
     (outline-4 ((t (:italic t :background "seashell" :slant italic))))
     (outline-5 ((t (:foreground "black"))))
     (outline-6 ((t (:foreground "darkblue"))))
     (outline-7 ((t (:foreground "black"))))
     (outline-8 ((t (:background "lemonChiffon"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "white" :foreground "red"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-scroll-bar-background-face ((t (:background "gray10"))))
     (popup-scroll-bar-foreground-face ((t (:background "#0A0A0A"))))
     (popup-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-tip-face ((t (:background "gray10" :foreground "white"))))
     (primary-selection ((t (:background "sienna" :foreground "light cyan"))))
     (pulse-highlight-face ((t (:background "#FFFFAA"))))
     (pulse-highlight-start-face ((t (:background "#FFFFAA"))))
     (query-replace ((t (:background "gray10"))))
     (rainbow-delimiters-depth-1-face ((t (:foreground "dark red"))))
     (rainbow-delimiters-depth-2-face ((t (:foreground "dark green"))))
     (rainbow-delimiters-depth-3-face ((t (:foreground "purple"))))
     (rainbow-delimiters-depth-4-face ((t (:foreground "DarkOrange4"))))
     (rainbow-delimiters-depth-5-face ((t (:foreground "magenta"))))
     (rainbow-delimiters-depth-6-face ((t (:foreground "blue4"))))
     (rainbow-delimiters-depth-7-face ((t (:foreground "orange"))))
     (rainbow-delimiters-depth-8-face ((t (:foreground "slate blue"))))
     (rainbow-delimiters-depth-9-face ((t (:foreground "turquoise4"))))
     (rainbow-delimiters-unmatched-face ((t (:foreground "white"))))
     (region ((t (:background "lavender" :foreground "black"))))
     (sclang-server-running-face ((t (:foreground "red"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray90"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (sp-pair-overlay-face ((t (:background "grey20"))))
     (sp-wrap-overlay-face ((t (:background "green"))))
     (sp-wrap-tag-overlay-face ((t (:background "grey20"))))
     (speedbar-button-face ((t (:foreground "#00ff00"))))
     (speedbar-directory-face ((t (:foreground "#00ff00"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "#00ff00" :foreground "purple"))))
     (speedbar-selected-face ((t (:foreground "deeppink" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (success ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (tabbar-button ((t (:background "grey75" :foreground "black" :box (:line-width 1 :color "white" :style released-button) :height 2.0 :family "helv"))))
     (tabbar-button-highlight ((t (:background "gray75" :foreground "black" :height 1.0 :family "helv"))))
     (tabbar-default ((t (:background "gray75" :foreground "black" :height 1.0 :family "helv"))))
     (tabbar-highlight ((t (:underline nil))))
     (tabbar-modified ((t (:italic t :background "gray75" :foreground "black" :box (:line-width 8 :color "grey80" :style released-button) :underline nil :slant italic :weight normal :height 0.8 :family "helv"))))
     (tabbar-selected ((t (:background "gray75" :foreground "black" :box (:line-width 5 :color "grey80" :style pressed-button) :height 1.2 :family "helv"))))
     (tabbar-separator ((t (:background "gray75" :foreground "gray75" :height 2.0 :family "helv"))))
     (tabbar-unselected ((t (:background "gray75" :foreground "black" :box (:line-width 5 :color "grey80" :style released-button) :height 0.8 :family "helv"))))
     (term ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-color-black ((t (:background "black" :foreground "black"))))
     (term-color-blue ((t (:background "#4c83ff" :foreground "#4c83ff"))))
     (term-color-cyan ((t (:background "cyan3" :foreground "cyan3"))))
     (term-color-green ((t (:background "green3" :foreground "green3"))))
     (term-color-magenta ((t (:background "magenta3" :foreground "magenta3"))))
     (term-color-red ((t (:background "red3" :foreground "red3"))))
     (term-color-white ((t (:background "white" :foreground "white"))))
     (term-color-yellow ((t (:background "yellow3" :foreground "yellow3"))))
     (term-underline ((t (:underline t))))
     (text-cursor ((t (:background "#aa0000" :foreground "black"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (:background "gray16" :foreground "#00ff00"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:background "black" :foreground "deep pink"))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (undo-tree-visualizer-unmodified-face ((t (:foreground "cyan"))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (:background "black" :foreground "gray10"))))
     (vertical-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (vhl/default-face ((t (:background "gray10"))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (wc-goal-face ((t (:background "mistyRose" :foreground "black"))))
     (which-func ((t (:bold t :underline t :weight bold))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "LemonChiffon3" :foreground "lightgray"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:foreground "lightgray" :weight normal))))
     (whitespace-space ((t (:background "LightYellow" :foreground "lightgray"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "beige" :foreground "lightgray"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (window-number-face ((t (:background "grey10" :foreground "#4c83ff"))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "lavender" :foreground "black"))))
     (yas/field-highlight-face ((t (:background "deep pink" :foreground "black"))))
     (zmacs-region ((t (:background "sienna" :foreground "light cyan")))))))
(add-to-list 'color-themes '(my-color-theme  "NG Light" "Nick Gonzalez"))
(provide 'my-color-theme)
