(eval-when-compile    (require 'color-theme))
(defun my-color-theme-dark ()
  "Color theme by Nicholas Gonzalez, created 2014-12-09."
  (interactive)
  (color-theme-install
   '(my-color-theme-dark
     ((Background-mode . light)
      (background-color . "black")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "white")
      (foreground-color . "cornsilk")
      (mouse-color . "black")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((ac-fuzzy-cursor-color . "red")
      (apropos-match-face . secondary-selection)
      (browse-kill-ring-current-entry-face . highlight)
      (browse-kill-ring-inserted-item-face . highlight)
      (browse-kill-ring-separator-face . bold)
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "black")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (eval-sexp-fu-flash-error-face . eval-sexp-fu-flash-error)
      (eval-sexp-fu-flash-face . eval-sexp-fu-flash)
      (gnus-mouse-face . highlight)
      (gnus-summary-selected-face . gnus-summary-selected-face)
      (hl-line-face . hl-line)
      (ibuffer-deletion-face . font-lock-type-face)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . font-lock-warning-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (magit-item-highlight-face . magit-item-highlight)
      (org-goto-interface . outline)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight)
      (win-switch-feedback-background-color . "DeepPink3")
      (win-switch-feedback-foreground-color . "black"))
     (default ((t (:stipple nil :background "black" :foreground "cornsilk" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (Buffer-menu-buffer-face ((t (nil))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Highline-face ((t (:background "SeaGreen"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (ac-candidate-face ((t (:background "gray60" :foreground "black"))))
     (ac-candidate-mouse-face ((t (:background "blue" :foreground "white"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "gray60" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "black"))))
     (ac-nrepl-candidate-face ((t (:background "gray60" :foreground "black"))))
     (ac-nrepl-selection-face ((t (:background "deep pink" :foreground "black"))))
     (ac-selection-face ((t (:background "deep pink" :foreground "black"))))
     (ac-yasnippet-candidate-face ((t (:background "gray60" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:background "deep pink" :foreground "black"))))
     (ace-jump-face-background ((t (:foreground "gray40"))))
     (ace-jump-face-foreground ((t (:foreground "red" :underline nil))))
     (antlr-font-lock-keyword-face ((t (nil))))
     (antlr-font-lock-literal-face ((t (nil))))
     (antlr-font-lock-ruledef-face ((t (nil))))
     (antlr-font-lock-ruleref-face ((t (nil))))
     (antlr-font-lock-tokendef-face ((t (nil))))
     (antlr-font-lock-tokenref-face ((t (nil))))
     (apropos-function-button ((t (:foreground "#4c83ff"))))
     (apropos-keybinding ((t (:underline t))))
     (apropos-misc-button ((t (:foreground "yellow3"))))
     (apropos-property ((t (:foreground "black"))))
     (apropos-symbol ((t (:foreground "deep pink"))))
     (apropos-variable-button ((t (:foreground "dark green"))))
     (bbdb-company ((t (:foreground "pale green"))))
     (bbdb-field-name ((t (:foreground "medium sea green"))))
     (bbdb-field-value ((t (:foreground "dark sea green"))))
     (bbdb-name ((t (:bold t :foreground "pale green" :weight bold))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "cornsilk" :foreground "black"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :foreground "white" :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "black"))))
     (border ((t (:background "Grey"))))
     (border-glyph ((t (nil))))
     (browse-kill-ring-current-entry-face ((t (:background "gray10"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (button ((t (:underline t))))
     (c-annotation-face ((t (:foreground "darkblue"))))
     (calc-nonselected-face ((t (:italic t :foreground "grey50" :slant italic))))
     (calc-selected-face ((t (:bold t :weight bold))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgment ((t (:italic t :background "seashell" :foreground "LightBlue" :slant italic))))
     (change-log-conditionals ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-date ((t (:background "lemonChiffon" :foreground "LightSalmon"))))
     (change-log-email ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-file ((t (:bold t :foreground "Aquamarine" :underline t :weight bold))))
     (change-log-function ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-list ((t (:foreground "Salmon"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (cider-docview-emphasis-face ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline t :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-docview-literal-face ((t (:background "lemonChiffon"))))
     (cider-docview-strong-face ((t (:bold t :stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline t :slant normal :weight bold :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-docview-table-border-face ((t (:foreground "grey50"))))
     (cider-error-highlight-face ((t (:background "color-52"))))
     (cider-repl-err-output-face ((t (:foreground "deeppink"))))
     (cider-repl-input-face ((t (:bold t :weight bold))))
     (cider-repl-output-face ((t (:background "black" :italic t :slant italic))))
     (cider-repl-prompt-face ((t (:foreground "blue"))))
     (cider-repl-result-face ((t (nil))))
     (cider-stacktrace-error-class-face ((t (:bold t :background "white" :foreground "Red" :weight bold))))
     (cider-stacktrace-error-message-face ((t (:background "blackg"))))
     (cider-stacktrace-face ((t (:stipple nil :background "ivory" :foreground "black" :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-stacktrace-filter-hidden-face ((t (:background "black" :foreground "ivory" :underline nil :weight normal))))
     (cider-stacktrace-filter-shown-face ((t (:foreground "#4c83ff"))))
     (cider-stacktrace-fn-face ((t (:bold t :stipple nil :background "ivory" :foreground "black" :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (cider-stacktrace-ns-face ((t (:italic t :background "black" :foreground "ivory" :slant italic))))
     (cider-test-error-face ((t (:background "orange1"))))
     (cider-test-failure-face ((t (:background "orange red"))))
     (cider-test-success-face ((t (:background "green" :foreground "black"))))
     (cider-warning-highlight-face ((t (:underline (:style wave :color "yellow")))))
     (clear-case-mode-string-face ((t (:bold t :background "grey" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :weight bold :height 0.9 :family "Arial"))))
     (clearcase-dired-checkedout-face ((t (nil))))
     (clojure-character-face ((t (:background "lemonChiffon"))))
     (clojure-interop-method-face ((t (:background "pale green" :foreground "dark slate blue"))))
     (clojure-keyword-face ((t (:foreground "slate blue"))))
     (clojure-test-error-face ((t (:background "orange1"))))
     (clojure-test-failure-face ((t (:background "orange red"))))
     (clojure-test-success-face ((t (:background "green" :foreground "black"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:background "lemonChiffon"))))
     (compilation-error ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-info ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-line-number ((t (:foreground "blue"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (:bold t :foreground "maroon" :weight bold))))
     (cparen-around-begin-face ((t (:foreground "maroon"))))
     (cparen-around-conditional-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (cparen-around-define-face ((t (:bold t :foreground "Blue" :weight bold))))
     (cparen-around-lambda-face ((t (:foreground "LightSeaGreen"))))
     (cparen-around-letdo-face ((t (:bold t :foreground "LightSeaGreen" :weight bold))))
     (cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
     (cparen-around-set!-face ((t (:foreground "OrangeRed"))))
     (cparen-around-syntax-rules-face ((t (:foreground "Magenta"))))
     (cparen-around-vector-face ((t (:foreground "chocolate"))))
     (cparen-binding-face ((t (:foreground "ForestGreen"))))
     (cparen-binding-list-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (cparen-conditional-clause-face ((t (:foreground "RoyalBlue"))))
     (cparen-normal-paren-face ((t (:foreground "grey50"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-invalid-face ((t (nil))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "white"))))
     (custom-button-face ((t (:foreground "white"))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:background "skyblue" :foreground "wheat"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation-face ((t (:foreground "white"))))
     (custom-face-tag-face ((t (:foreground "white" :underline t))))
     (custom-group-tag-face ((t (:foreground "skyblue" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:foreground "blue"))))
     (custom-state-face ((t (:foreground "light green"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:foreground "skyblue" :underline t))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (nil))))
     (diary ((t (:bold t :foreground "orange" :weight bold))))
     (diff-added ((t (:foreground "Green"))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey70"))))
     (diff-file-header ((t (:background "gray10" :foreground "deep pink"))))
     (diff-function ((t (:background "gray10" :foreground "grey70"))))
     (diff-header ((t (:background "gray10" :foreground "#4c83ff"))))
     (diff-hunk-header ((t (:background "gray10" :foreground "light salmon"))))
     (diff-index ((t (:bold t :background "gray10" :foreground "deep pink" :weight bold))))
     (diff-indicator-added ((t (:foreground "green"))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:foreground "red"))))
     (diff-nonexistent ((t (:bold t :background "gray10" :foreground "deep pink" :weight bold))))
     (diff-refine-added ((t (:background "#aaffaa"))))
     (diff-refine-change ((t (:background "#ffff55"))))
     (diff-refine-removed ((t (:background "#ffbbbb"))))
     (diff-removed ((t (:foreground "Red"))))
     (dircolors-face-asm ((t (:foreground "Tan"))))
     (dircolors-face-backup ((t (:foreground "darkslategrey"))))
     (dircolors-face-compress ((t (:foreground "firebrick"))))
     (dircolors-face-dir ((t (:foreground "orange"))))
     (dircolors-face-doc ((t (:foreground "red"))))
     (dircolors-face-dos ((t (:foreground "darkred"))))
     (dircolors-face-emacs ((t (:foreground "purple"))))
     (dircolors-face-exec ((t (:foreground "red"))))
     (dircolors-face-html ((t (:foreground "magenta"))))
     (dircolors-face-img ((t (:foreground "yellow"))))
     (dircolors-face-lang ((t (:foreground "lightblue"))))
     (dircolors-face-lang-interface ((t (:foreground "deepskyblue"))))
     (dircolors-face-make ((t (:foreground "seagreen"))))
     (dircolors-face-objet ((t (:foreground "orangered"))))
     (dircolors-face-package ((t (:foreground "firebrick"))))
     (dircolors-face-paddb ((t (:foreground "Orange"))))
     (dircolors-face-ps ((t (:foreground "brown"))))
     (dircolors-face-sound ((t (:foreground "yellow"))))
     (dircolors-face-tar ((t (:foreground "firebrick"))))
     (dircolors-face-text ((t (:foreground "red"))))
     (dircolors-face-yacc ((t (:foreground "dodgerblue"))))
     (dired-directory ((t (:bold t :underline t :weight bold))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (nil))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "LightSalmon"))))
     (dired-face-socket ((t (:foreground "LightBlue"))))
     (dired-face-symlink ((t (:foreground "gray95"))))
     (dired-flagged ((t (:bold t :foreground "Red1" :weight bold))))
     (dired-header ((t (:foreground "black"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "darkblue"))))
     (dired-marked ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (dired-perm-write ((t (:foreground "#B2B2B2"))))
     (dired-symlink ((t (:foreground "blue"))))
     (dired-warning ((t (:bold t :foreground "Red" :weight bold))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (nil))))
     (ebrowse-member-attribute-face ((t (nil))))
     (ebrowse-member-class-face ((t (nil))))
     (ebrowse-progress-face ((t (nil))))
     (ebrowse-root-class-face ((t (nil))))
     (ebrowse-tree-mark-face ((t (nil))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (edb-inter-field-face ((t (:foreground "deep sky blue"))))
     (edb-normal-summary-face ((t (:foreground "gold"))))
     (ediff-current-diff-A ((t (:background "#ffdddd"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "#ddffdd"))))
     (ediff-current-diff-C ((t (:background "#ffffaa"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "indianred" :foreground "white"))))
     (ediff-even-diff-A ((t (:background "dark green"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "dark red"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-A ((t (:background "light gray" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Gray" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Gray" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light gray" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "#ffbbbb"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "#aaffaa"))))
     (ediff-fine-diff-C ((t (:background "#ffff55"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "dark green"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "dark red"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-A ((t (:background "Gray" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light gray" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light gray" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Gray" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "coral" :underline "coral" :weight bold))))
     (emacs-wiki-link-face ((t (:bold t :foreground "cyan" :underline "cyan" :weight bold))))
     (epa-field-body ((t (:italic t :slant italic))))
     (epa-field-name ((t (:bold t :weight bold))))
     (epa-mark ((t (:bold t :foreground "red" :weight bold))))
     (epa-string ((t (:foreground "blue4"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :slant italic))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:foreground "#FBDE2D"))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :background "Red" :foreground "IndianRed" :weight bold))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "light blue"))))
     (erc-inverse-face ((t (:background "steel blue" :foreground "White"))))
     (erc-keyword-face ((t (:foreground "deep pink"))))
     (erc-my-nick-face ((t (:bold t :foreground "deep pink" :weight bold))))
     (erc-nick-default-face ((t (:foreground "grey57"))))
     (erc-nick-msg-face ((t (:foreground "deep pink"))))
     (erc-notice-face ((t (:bold t :foreground "light salmon" :weight bold))))
     (erc-pal-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "black" :foreground "light blue" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (error ((t (:bold t :foreground "Red1" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "medium purple" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "dim gray"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "medium slate blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "violet"))))
     (eshell-ls-product-face ((t (:foreground "light steel blue"))))
     (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
     (eshell-ls-special-face ((t (:bold t :foreground "gold" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "white" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
     (eshell-prompt-face ((t (:bold t :foreground "light sky blue" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (eval-sexp-fu-flash ((t (:background "grey15" :foreground "DeepPink3"))))
     (eval-sexp-fu-flash-error ((t (:bold t :foreground "red" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (extra-whitespace-face ((t (:background "pale green"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (nil))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (nil))))
     (fl-function-name-face ((t (nil))))
     (fl-keyword-face ((t (nil))))
     (fl-string-face ((t (nil))))
     (fl-type-face ((t (nil))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flx-highlight-face ((t (:background "black" :foreground "deep pink"))))
     (flymake-errline ((t (:bold t :foreground "Red1" :weight bold))))
     (flymake-warnline ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "navy"))))
     (font-latex-sedate-face ((t (:foreground "Gray85"))))
     (font-latex-string-face ((t (:foreground "orange"))))
     (font-latex-warning-face ((t (:foreground "gold"))))
     (font-lock-builtin-face ((t (:bold t :foreground "medium spring green" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:background "gray10" :foreground "firebrick"))))
     (font-lock-comment-face ((t (:italic t :foreground "red" :slant italic))))
     (font-lock-constant-face ((t (:bold t :foreground "salmon" :weight bold))))
     (font-lock-doc-face ((t (:italic t :background "gray15" :foreground "light sky blue" :slant italic))))
     (font-lock-doc-string-face ((t (:foreground "sky blue"))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "turquoise" :underline t :weight bold :height 1.2))))
     (font-lock-keyword-face ((t (:bold t :foreground "green" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (nil))))
     (font-lock-other-type-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:bold t :foreground "tomato" :weight bold :height 1.0))))
     (font-lock-reference-face ((t (:bold t :foreground "pale green" :weight bold :height 1.1))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-special-comment-face ((t (nil))))
     (font-lock-special-keyword-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "ivory3"))))
     (font-lock-type-face ((t (:bold t :foreground "white" :underline t :weight bold))))
     (font-lock-variable-name-face ((t (:italic t :bold t :foreground "gold" :slant italic :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "gold" :weight bold))))
     (fringe ((t (:background "Grey15"))))
     (git-commit-branch-face ((t (:background "black" :foreground "#FF6400"))))
     (git-commit-comment-action-face ((t (:background "black" :foreground "#FF6400"))))
     (git-commit-comment-file-face ((t (:background "orange"))))
     (git-commit-comment-heading-face ((t (:background "black" :foreground "deep pink"))))
     (git-commit-known-pseudo-header-face ((t (:foreground "blue"))))
     (git-commit-no-branch-face ((t (:background "black" :foreground "#FF6400"))))
     (git-commit-nonempty-second-line-face ((t (:background "black" :foreground "#FBDE2D"))))
     (git-commit-note-face ((t (:background "orange"))))
     (git-commit-overlong-summary-face ((t (:bold t :foreground "Red" :weight bold))))
     (git-commit-pseudo-header-face ((t (:background "orange"))))
     (git-commit-summary-face ((t (:background "black" :foreground "white"))))
     (git-gutter:added ((t (:background "gray5" :foreground "#61CE3C"))))
     (git-gutter:deleted ((t (:background "gray5" :foreground "gray10"))))
     (git-gutter:modified ((t (:background "gray5" :foreground "#4c83ff"))))
     (git-gutter:separator ((t (:bold t :foreground "cyan" :weight bold))))
     (git-gutter:unchanged ((t (:background "grey5"))))
     (git-rebase-description ((t (nil))))
     (git-rebase-hash ((t (:foreground "firebrick"))))
     (git-rebase-killed-action ((t (:italic t :background "seashell" :strike-through t :slant italic))))
     (glsl-builtin-face ((t (:foreground "#FF6400"))))
     (glsl-keyword-face ((t (:foreground "#FBDE2D"))))
     (glsl-type-face ((t (:foreground "#4c83ff"))))
     (glsl-variable-name-face ((t (:foreground "grey57"))))
     (glyphless-char ((t (:height 0.6))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "light cyan"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "light blue"))))
     (gnus-cite-face-3 ((t (:foreground "light yellow"))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:background "goldenrod4" :foreground "white"))))
     (gnus-emphasis-underline-bold ((t (:bold t :background "yellow" :foreground "black" :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :background "yellow" :foreground "black" :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :background "yellow" :foreground "black" :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1 ((t (:bold t :foreground "white" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "gray80"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "lightcyan" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "lightcyan"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "tan" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "tan"))))
     (gnus-group-mail-low ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine4"))))
     (gnus-group-news-1 ((t (:bold t :foreground "white" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "white"))))
     (gnus-group-news-2 ((t (:bold t :foreground "lightcyan" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "lightcyan"))))
     (gnus-group-news-3 ((t (:bold t :foreground "tan" :weight bold))))
     (gnus-group-news-3-empty ((t (:foreground "tan"))))
     (gnus-group-news-4 ((t (:bold t :foreground "white" :weight bold))))
     (gnus-group-news-4-empty ((t (:foreground "white"))))
     (gnus-group-news-5 ((t (:bold t :foreground "wheat" :weight bold))))
     (gnus-group-news-5-empty ((t (:foreground "wheat"))))
     (gnus-group-news-6 ((t (:bold t :foreground "tan" :weight bold))))
     (gnus-group-news-6-empty ((t (:foreground "tan"))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-header-content-face ((t (:italic t :foreground "plum1" :slant italic))))
     (gnus-header-from-face ((t (:bold t :foreground "wheat" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "gold" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "wheat" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "red" :weight bold))))
     (gnus-picon-face ((t (nil))))
     (gnus-picon-xbm-face ((t (nil))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight bold))))
     (gnus-signature-face ((t (:italic t :foreground "maroon" :slant italic))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-summary-cancelled ((t (:background "gray" :foreground "black"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "gray70" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "cyan4" :weight bold))))
     (gnus-summary-high-unread ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :bold t :foreground "gray70" :slant italic :weight bold))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:bold t :foreground "gray70" :weight bold))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (:bold t :weight bold))))
     (gnus-summary-selected ((t (:background "deepskyblue4" :underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (grep-context-face ((t (:background "deep pink" :foreground "black"))))
     (grep-hit-face ((t (:background "red" :foreground "black"))))
     (grep-match-face ((t (:background "deep pink" :foreground "black"))))
     (gui-button-face ((t (:background "cyan" :foreground "#65889C"))))
     (gui-element ((t (:background "gray10" :foreground "#96CBFE"))))
     (haskell-constructor-face ((t (:foreground "black"))))
     (haskell-default-face ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (haskell-definition-face ((t (:bold t :underline t :weight bold))))
     (haskell-keyword-face ((t (:foreground "blue"))))
     (haskell-literate-comment-face ((t (:background "orange"))))
     (haskell-operator-face ((t (:foreground "black"))))
     (haskell-pragma-face ((t (:italic t :background "seashell" :slant italic))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil :overline "blueviolet" :underline "blueviolet"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (nil))))
     (hi-black-hb ((t (nil))))
     (hi-blue ((t (nil))))
     (hi-blue-b ((t (nil))))
     (hi-green ((t (nil))))
     (hi-green-b ((t (nil))))
     (hi-pink ((t (nil))))
     (hi-red-b ((t (nil))))
     (hi-yellow ((t (nil))))
     (hideshowvis-hidable-face ((t (:foreground "#ccc" :box 1))))
     (highlight ((t (:background "darkslategray" :foreground "wheat"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "gray35"))))
     (hl-line ((t (:background "gray10"))))
     (hl-sexp-face ((t (:background "grey9"))))
     (hlt-property-highlight ((t (:background "Wheat"))))
     (holiday ((t (:background "red"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (html-helper-bold-face ((t (:bold t :foreground "wheat" :weight bold))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (nil))))
     (html-helper-italic-face ((t (:italic t :foreground "spring green" :slant italic))))
     (html-helper-underline-face ((t (:foreground "cornsilk" :underline t))))
     (html-tag-face ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (hyper-apropos-documentation ((t (:foreground "LightSalmon"))))
     (hyper-apropos-heading ((t (nil))))
     (hyper-apropos-hyperlink ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (hyper-apropos-major-heading ((t (nil))))
     (hyper-apropos-section-heading ((t (nil))))
     (hyper-apropos-warning ((t (nil))))
     (ibuffer-deletion-face ((t (nil))))
     (ibuffer-git-add-face ((t (:foreground "green"))))
     (ibuffer-git-del-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (nil))))
     (idlwave-help-link-face ((t (nil))))
     (idlwave-shell-bp-face ((t (nil))))
     (ido-first-match ((t (:background "black" :foreground "deep pink"))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red" :weight bold))))
     (ido-indicator ((t (:background "deep pink" :foreground "black"))))
     (ido-indicator-face ((t (nil))))
     (ido-only-match ((t (:background "black" :foreground "deep pink"))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:background "black" :foreground "gray60"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (ido-virtual ((t (:foreground "black"))))
     (info-header-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-header-xref ((t (:bold t :foreground "sky blue" :weight bold))))
     (info-menu-5 ((t (:underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-node ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (info-xref ((t (:bold t :foreground "plum" :weight bold))))
     (isearch ((t (:background "slate blue" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (iswitchb-current-match ((t (:bold t :underline t :weight bold))))
     (iswitchb-invalid-regexp ((t (:bold t :foreground "Red" :weight bold))))
     (iswitchb-single-match ((t (:italic t :background "seashell" :slant italic))))
     (iswitchb-virtual-matches ((t (:foreground "black"))))
     (italic ((t (nil))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (js2-error ((t (:foreground "red"))))
     (js2-external-variable ((t (:foreground "orange"))))
     (js2-function-call ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (js2-function-param ((t (:foreground "SeaGreen"))))
     (js2-instance-member ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter ((t (:foreground "dark khaki"))))
     (js2-jsdoc-html-tag-name ((t (:foreground "rosybrown"))))
     (js2-jsdoc-tag ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value ((t (:foreground "PeachPuff3"))))
     (js2-private-function-call ((t (:foreground "goldenrod"))))
     (js2-private-member ((t (:foreground "PeachPuff3"))))
     (js2-warning ((t (:underline "orange"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "RoyalBlue3" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (list-mode-item-selected ((t (nil))))
     (log-edit-header ((t (:foreground "blue"))))
     (log-edit-summary ((t (:bold t :underline t :weight bold))))
     (log-edit-unknown-header ((t (:italic t :background "seashell" :slant italic))))
     (log-view-file-face ((t (nil))))
     (log-view-message-face ((t (:foreground "light salmon"))))
     (magenta ((t (nil))))
     (magit-branch ((t (:foreground "gold"))))
     (magit-cherry-equivalent ((t (:foreground "magenta"))))
     (magit-cherry-unmatched ((t (:foreground "cyan"))))
     (magit-diff-add ((t (:foreground "green"))))
     (magit-diff-del ((t (:foreground "red"))))
     (magit-diff-file-header ((t (:background "gray10" :foreground "deep pink"))))
     (magit-diff-hunk-header ((t (:foreground "orange"))))
     (magit-diff-merge-current ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-merge-diff3-separator ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-merge-proposed ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-merge-separator ((t (:background "pale green" :foreground "dark slate blue"))))
     (magit-diff-none ((t (:foreground "grey50"))))
     (magit-item-highlight ((t (:background "gray15"))))
     (magit-item-mark ((t (:background "mistyRose" :foreground "black"))))
     (magit-key-mode-args-face ((t (:background "gray85"))))
     (magit-key-mode-button-face ((t (:foreground "black"))))
     (magit-key-mode-header-face ((t (:foreground "blue"))))
     (magit-key-mode-switch-face ((t (:bold t :foreground "Red" :weight bold))))
     (magit-log-author ((t (:foreground "firebrick"))))
     (magit-log-date ((t (nil))))
     (magit-log-graph ((t (:foreground "grey11"))))
     (magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-head-label-bisect-skip ((t (:background "light goldenrod" :foreground "dark goldenrod" :box 1))))
     (magit-log-head-label-default ((t (:background "Grey50" :box 1))))
     (magit-log-head-label-head ((t (:background "Grey20" :foreground "White" :box 1))))
     (magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-head-label-wip ((t (:background "Grey07" :foreground "LightSkyBlue4" :box 1))))
     (magit-log-message ((t (nil))))
     (magit-log-reflog-label-amend ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-reflog-label-checkout ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-reflog-label-cherry-pick ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-reflog-label-commit ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-reflog-label-merge ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-reflog-label-other ((t (:background "Grey50" :box 1))))
     (magit-log-reflog-label-rebase ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-reflog-label-remote ((t (:background "Grey50" :box 1))))
     (magit-log-reflog-label-reset ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-sha1 ((t (:foreground "firebrick"))))
     (magit-process-ng ((t (:foreground "red"))))
     (magit-process-ok ((t (:foreground "green"))))
     (magit-section-title ((t (:foreground "deep pink"))))
     (magit-signature-bad ((t (:foreground "red"))))
     (magit-signature-good ((t (:foreground "green"))))
     (magit-signature-none ((t (nil))))
     (magit-signature-untrusted ((t (:foreground "cyan"))))
     (magit-tag ((t (:background "LemonChiffon1" :foreground "goldenrod4"))))
     (magit-whitespace-warning-face ((t (:background "red"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (nil))))
     (man-heading ((t (nil))))
     (man-italic ((t (nil))))
     (man-xref ((t (nil))))
     (markdown-blockquote-face ((t (:background "lemonChiffon"))))
     (markdown-bold-face ((t (:foreground "#FF6400"))))
     (markdown-comment-face ((t (:italic t :background "seashell" :slant italic))))
     (markdown-header-face ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-1 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-2 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-3 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-4 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-5 ((t (:bold t :underline t :weight bold))))
     (markdown-header-face-6 ((t (:bold t :underline t :weight bold))))
     (markdown-inline-code-face ((t (:foreground "#4c83ff"))))
     (markdown-italic-face ((t (:italic t :foreground "#FF6400" :slant italic))))
     (markdown-link-face ((t (:foreground "#FBDE2D"))))
     (markdown-link-title-face ((t (:italic t :background "seashell" :slant italic))))
     (markdown-list-face ((t (:foreground "#8B8989"))))
     (markdown-math-face ((t (:background "lemonChiffon"))))
     (markdown-pre-face ((t (:foreground "#4c83ff"))))
     (markdown-reference-face ((t (:foreground "black"))))
     (markdown-url-face ((t (:foreground "#61CE3C"))))
     (match ((t (:background "blackn" :foreground "deep pink"))))
     (mc/cursor-face ((t (nil))))
     (mc/region-face ((t (:background "lavender" :foreground "black"))))
     (menu ((t (:background "MidnightBlue" :foreground "Grey"))))
     (message-cited-text ((t (:foreground "plum1"))))
     (message-header-cc ((t (:bold t :foreground "ivory" :weight bold))))
     (message-header-contents ((t (nil))))
     (message-header-name ((t (:foreground "light sky blue"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "lavender blush" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "pale turquoise"))))
     (message-header-subject ((t (:bold t :foreground "papaya whip" :weight bold))))
     (message-header-to ((t (:bold t :foreground "floral white" :weight bold))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-headers ((t (nil))))
     (message-highlighted-header-contents ((t (nil))))
     (message-mml ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (message-separator ((t (:foreground "sandy brown"))))
     (message-url ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (nil))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :overline "blueviolet" :underline "blueviolet"))))
     (mode-line-buffer-id ((t (:background "tan" :foreground "black"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:italic t :background "black" :foreground "navy" :box (:line-width -1 :color "grey75") :overline "blueviolet" :underline "blueviolet" :slant oblique :weight light))))
     (modeline ((t (:background "tan" :foreground "black"))))
     (modeline-mousable ((t (:background "tan" :foreground "black"))))
     (modeline-mousable-minor-mode ((t (:background "tan" :foreground "black"))))
     (mouse ((t (:background "Grey"))))
     (mpg123-face-cur ((t (nil))))
     (mpg123-face-slider ((t (nil))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "PaleTurquoise"))))
     (naeu-blue-face ((t (:background "black" :foreground "medium slate blue"))))
     (naeu-green-face ((t (:background "black" :foreground "green"))))
     (naeu-grey-face ((t (:background "black" :foreground "gray30"))))
     (naeu-orange-face ((t (:background "black" :foreground "#FBDE2D"))))
     (naeu-pink-face ((t (:background "black" :foreground "deep pink"))))
     (naeu-red-face ((t (:background "black" :foreground "orange"))))
     (next-error ((t (:background "deep pink" :foreground "black"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (org-agenda-calendar-event ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-agenda-calendar-sexp ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-agenda-clocking ((t (:background "yellow"))))
     (org-agenda-column-dateline ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-agenda-current-time ((t (:foreground "DarkGoldenrod"))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-diary ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-filter-category ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-agenda-filter-regexp ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-agenda-filter-tags ((t (:bold t :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-agenda-restriction-lock ((t (:background "#eeeeee"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:italic t :background "seashell" :slant italic))))
     (org-block-end-line ((t (:italic t :background "seashell" :slant italic))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-checkbox-statistics-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-clock-overlay ((t (:background "yellow1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-date-selected ((t (:background "Red1"))))
     (org-default ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (org-document-info ((t (:foreground "midnight blue"))))
     (org-document-info-keyword ((t (:foreground "grey50"))))
     (org-document-title ((t (:bold t :foreground "midnight blue" :weight bold))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "white"))))
     (org-latex-and-related ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:bold t :underline t :weight bold))))
     (org-level-2 ((t (:foreground "yellow"))))
     (org-level-3 ((t (:foreground "blue"))))
     (org-level-4 ((t (:italic t :background "seashell" :slant italic))))
     (org-level-5 ((t (:foreground "black"))))
     (org-level-6 ((t (:foreground "slate"))))
     (org-level-7 ((t (:foreground "black"))))
     (org-level-8 ((t (:background "lemonChiffon"))))
     (org-link ((t (:foreground "RoyalBlue3" :underline t))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:foreground "SaddleBrown"))))
     (org-meta-line ((t (:italic t :background "seashell" :slant italic))))
     (org-mode-line-clock ((t (:bold t :overline "blueviolet" :box (:line-width -1 :style released-button) :background "mistyRose" :foreground "navy" :underline t :weight bold))))
     (org-mode-line-clock-overrun ((t (:bold t :overline "blueviolet" :box (:line-width -1 :style released-button) :background "red" :foreground "navy" :underline t :weight bold))))
     (org-priority ((t (:foreground "blue"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey50"))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "blue"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-tag-group ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-verse ((t (:foreground "grey50"))))
     (org-warning ((t (:bold t :foreground "Red" :weight bold))))
     (outline-1 ((t (:bold t :underline t :weight bold))))
     (outline-2 ((t (:foreground "black"))))
     (outline-3 ((t (:foreground "blue"))))
     (outline-4 ((t (:italic t :background "seashell" :slant italic))))
     (outline-5 ((t (:foreground "black"))))
     (outline-6 ((t (:foreground "darkblue"))))
     (outline-7 ((t (:foreground "black"))))
     (outline-8 ((t (:background "lemonChiffon"))))
     (overlay-empty-face ((t (nil))))
     (p4-diff-del-face ((t (nil))))
     (paren-blink-off ((t (:foreground "gray"))))
     (paren-face ((t (nil))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
     (paren-mismatch-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (paren-no-match-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (pointer ((t (nil))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "black" :foreground "deep pink"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-menu-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-scroll-bar-background-face ((t (:background "gray10"))))
     (popup-scroll-bar-foreground-face ((t (:background "#0A0A0A"))))
     (popup-summary-face ((t (:background "lightgray" :foreground "dimgray"))))
     (popup-tip-face ((t (:background "gray10" :foreground "white"))))
     (primary-selection ((t (:background "dimgray"))))
     (pulse-highlight-face ((t (:background "#FFFFAA"))))
     (pulse-highlight-start-face ((t (:background "#FFFFAA"))))
     (query-replace ((t (:background "gray10"))))
     (rainbow-delimiters-depth-1-face ((t (:foreground "dark red"))))
     (rainbow-delimiters-depth-2-face ((t (:foreground "dark green"))))
     (rainbow-delimiters-depth-3-face ((t (:foreground "deep pink"))))
     (rainbow-delimiters-depth-4-face ((t (:foreground "yellow"))))
     (rainbow-delimiters-depth-5-face ((t (:foreground "green"))))
     (rainbow-delimiters-depth-6-face ((t (:foreground "light blue"))))
     (rainbow-delimiters-depth-7-face ((t (:foreground "orange"))))
     (rainbow-delimiters-depth-8-face ((t (:foreground "slate blue"))))
     (rainbow-delimiters-depth-9-face ((t (:foreground "light gray"))))
     (rainbow-delimiters-unmatched-face ((t (:foreground "white"))))
     (reb-match-0 ((t (nil))))
     (reb-match-1 ((t (nil))))
     (reb-match-2 ((t (nil))))
     (reb-match-3 ((t (nil))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "slategrey"))))
     (right-margin ((t (nil))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (nil))))
     (sclang-server-running-face ((t (:foreground "red"))))
     (scroll-bar ((t (:background "grey75" :foreground "#000000"))))
     (secondary-selection ((t (:background "deepskyblue4"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray90"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray90"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "orange"))))
     (sgml-end-tag-face ((t (:foreground "greenyellow"))))
     (sgml-entity-face ((t (:foreground "gold"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "yellow"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-shortref-face ((t (nil))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (shadow ((t (:foreground "grey50"))))
     (shell-option-face ((t (:foreground "blue"))))
     (shell-output-2-face ((t (:foreground "darkseagreen"))))
     (shell-output-3-face ((t (:foreground "slategray"))))
     (shell-output-face ((t (:foreground "palegreen"))))
     (shell-prompt-face ((t (:foreground "red"))))
     (show-block-face1 ((t (nil))))
     (show-block-face2 ((t (nil))))
     (show-block-face3 ((t (nil))))
     (show-block-face4 ((t (nil))))
     (show-block-face5 ((t (nil))))
     (show-block-face6 ((t (nil))))
     (show-block-face7 ((t (nil))))
     (show-block-face8 ((t (nil))))
     (show-block-face9 ((t (nil))))
     (show-paren-match ((t (:background "deepskyblue4"))))
     (show-paren-mismatch ((t (:bold t :background "red" :foreground "white" :weight bold))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (smerge-base-face ((t (nil))))
     (smerge-markers-face ((t (nil))))
     (smerge-mine-face ((t (nil))))
     (smerge-other-face ((t (nil))))
     (sp-pair-overlay-face ((t (:background "grey20"))))
     (sp-wrap-overlay-face ((t (:background "green"))))
     (sp-wrap-tag-overlay-face ((t (:background "grey20"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:bold t :foreground "cyan4" :weight bold))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (strokes-char-face ((t (nil))))
     (success ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (tabbar-button ((t (:background "grey75" :foreground "black" :box (:line-width 1 :color "white" :style released-button) :height 2.0 :family "helv"))))
     (tabbar-button-face ((t (nil))))
     (tabbar-button-highlight ((t (:background "gray75" :foreground "black" :height 1.0 :family "helv"))))
     (tabbar-default ((t (:background "gray75" :foreground "black" :height 1.0 :family "helv"))))
     (tabbar-default-face ((t (nil))))
     (tabbar-highlight ((t (:underline nil))))
     (tabbar-modified ((t (:italic t :background "gray75" :foreground "black" :box (:line-width 8 :color "grey80" :style released-button) :underline nil :slant italic :weight normal :height 0.8 :family "helv"))))
     (tabbar-selected ((t (:background "gray75" :foreground "black" :box (:line-width 5 :color "grey80" :style pressed-button) :height 1.2 :family "helv"))))
     (tabbar-selected-face ((t (nil))))
     (tabbar-separator ((t (:background "gray75" :foreground "gray75" :height 2.0 :family "helv"))))
     (tabbar-separator-face ((t (nil))))
     (tabbar-unselected ((t (:background "gray75" :foreground "black" :box (:line-width 5 :color "grey80" :style released-button) :height 0.8 :family "helv"))))
     (tabbar-unselected-face ((t (nil))))
     (template-message-face ((t (:bold t :weight bold))))
     (term ((t (:stipple nil :background "ivory" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Menlo"))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (nil))))
     (term-blue-face ((t (nil))))
     (term-blue-inv-face ((t (nil))))
     (term-blue-ul-face ((t (nil))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-color-black ((t (:background "black" :foreground "black"))))
     (term-color-blue ((t (:background "#4c83ff" :foreground "#4c83ff"))))
     (term-color-cyan ((t (:background "cyan3" :foreground "cyan3"))))
     (term-color-green ((t (:background "green3" :foreground "green3"))))
     (term-color-magenta ((t (:background "magenta3" :foreground "magenta3"))))
     (term-color-red ((t (:background "red3" :foreground "red3"))))
     (term-color-white ((t (:background "white" :foreground "white"))))
     (term-color-yellow ((t (:background "yellow3" :foreground "yellow3"))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyan-bold-face ((t (nil))))
     (term-cyan-face ((t (nil))))
     (term-cyan-inv-face ((t (nil))))
     (term-cyan-ul-face ((t (nil))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default ((t (:stipple nil :background "DarkSlateGray" :foreground "palegreen" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "lucida sans typewriter"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (nil))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (nil))))
     (term-default-ul-face ((t (nil))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (nil))))
     (term-green-face ((t (nil))))
     (term-green-inv-face ((t (nil))))
     (term-green-ul-face ((t (nil))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (nil))))
     (term-magenta-face ((t (nil))))
     (term-magenta-inv-face ((t (nil))))
     (term-magenta-ul-face ((t (nil))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (nil))))
     (term-red-face ((t (nil))))
     (term-red-inv-face ((t (nil))))
     (term-red-ul-face ((t (nil))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-white-bold-face ((t (nil))))
     (term-white-face ((t (nil))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (nil))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellow-bold-face ((t (nil))))
     (term-yellow-face ((t (nil))))
     (term-yellow-inv-face ((t (nil))))
     (term-yellow-ul-face ((t (nil))))
     (term-yellowbg ((t (:background "yellow"))))
     (tex-math-face ((t (nil))))
     (texinfo-heading-face ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:background "black" :foreground "deep pink"))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (undo-tree-visualizer-unmodified-face ((t (:foreground "cyan"))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (:background "black" :foreground "gray10"))))
     (vertical-divider ((t (:background "Gray"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-generic-/constant-face ((t (nil))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (nil))))
     (vhdl-font-lock-variable-face ((t (nil))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Gray50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Gray50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (nil))))
     (vhl/default-face ((t (:background "gray10"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "gray" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "gray80" :slant italic))))
     (vm-header-from-face ((t (:italic t :background "#65889C" :foreground "cyan" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (nil))))
     (vmpc-pre-sig-face ((t (:foreground "Aquamarine"))))
     (vmpc-sig-face ((t (:foreground "LightBlue"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (wc-goal-face ((t (:background "mistyRose" :foreground "black"))))
     (which-func ((t (:bold t :underline t :weight bold))))
     (white ((t (nil))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "LemonChiffon3" :foreground "lightgray"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:foreground "lightgray" :weight normal))))
     (whitespace-space ((t (:background "LightYellow" :foreground "lightgray"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "beige" :foreground "lightgray"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "gray20"))))
     (widget-inactive ((t (:foreground "wheat"))))
     (widget-single-line-field ((t (:background "gray20"))))
     (window-number-face ((t (:background "grey10" :foreground "#4c83ff"))))
     (woman-addition-face ((t (nil))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (nil))))
     (xrdb-option-name-face ((t (nil))))
     (xref-keyword-face ((t (:foreground "Cyan"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "lavender" :foreground "black"))))
     (yas/field-highlight-face ((t (:background "deep pink" :foreground "black"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "DarkSlateBlue")))))))
(add-to-list 'color-themes '(my-color-theme-dark  "NG Dark" "Nick Gonzalez"))
(provide 'my-color-theme-dark)
